<a href="https://colab.research.google.com/github/dinusariehewage-coder/ET3112-/blob/main/Q5(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

# Kernel parameters
kernel_size = 5
sigma = 2

# Create a grid of (x,y) coordinates
ax = np.arange(-(kernel_size // 2), kernel_size // 2 + 1, 1)
x, y = np.meshgrid(ax, ax)

# Compute Gaussian function
gaussian_kernel = np.exp(-(x**2 + y**2) / (2 * sigma**2))

# Normalize so sum = 1
gaussian_kernel /= np.sum(gaussian_kernel)

print("Normalized 5x5 Gaussian Kernel (σ=2):\n", gaussian_kernel)


Normalized 5x5 Gaussian Kernel (σ=2):
 [[0.02324684 0.03382395 0.03832756 0.03382395 0.02324684]
 [0.03382395 0.04921356 0.05576627 0.04921356 0.03382395]
 [0.03832756 0.05576627 0.06319146 0.05576627 0.03832756]
 [0.03382395 0.04921356 0.05576627 0.04921356 0.03382395]
 [0.02324684 0.03382395 0.03832756 0.03382395 0.02324684]]
