<a href="https://colab.research.google.com/github/dinusariehewage-coder/ET3112-/blob/main/Q6(b).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

sigma = 2
size = 5
k = size // 2

# Coordinate grid
x, y = np.meshgrid(np.arange(-k, k+1), np.arange(-k, k+1))

# Gaussian
G = (1 / (2 * np.pi * sigma**2)) * np.exp(-(x**2 + y**2) / (2 * sigma**2))

# Derivatives
Gx = -(x / sigma**2) * G
Gy = -(y / sigma**2) * G

# Normalize kernels (sum of absolute values = 1)
Gx = Gx / np.sum(np.abs(Gx))
Gy = Gy / np.sum(np.abs(Gy))

print("5×5 DoG kernel (x-direction):\n", Gx)
print("\n5×5 DoG kernel (y-direction):\n", Gy)



5×5 DoG kernel (x-direction):
 [[ 0.04413011  0.03210446 -0.         -0.03210446 -0.04413011]
 [ 0.06420893  0.04671172 -0.         -0.04671172 -0.06420893]
 [ 0.07275825  0.05293131 -0.         -0.05293131 -0.07275825]
 [ 0.06420893  0.04671172 -0.         -0.04671172 -0.06420893]
 [ 0.04413011  0.03210446 -0.         -0.03210446 -0.04413011]]

5×5 DoG kernel (y-direction):
 [[ 0.04413011  0.06420893  0.07275825  0.06420893  0.04413011]
 [ 0.03210446  0.04671172  0.05293131  0.04671172  0.03210446]
 [-0.         -0.         -0.         -0.         -0.        ]
 [-0.03210446 -0.04671172 -0.05293131 -0.04671172 -0.03210446]
 [-0.04413011 -0.06420893 -0.07275825 -0.06420893 -0.04413011]]
